Websellphone/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SellPhoneVIewModel.Common;
using System.Threading.Tasks;

namespace WebsellphoneAdmin.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        //View component
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

Websellphone/Controllers/Components/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Threading.Tasks;
using WebSellPhoneApiCaller.ApiCaller.ApiCategoryClient;

namespace Websellphone.Controllers.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public SideBarViewComponent(ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await _categoryApiClient.GetAll(CultureInfo.CurrentCulture.Name);
            return View(items);
        }
    }
}

Websellphone/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SellPhoneVIewModel.Catalog.Products;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Websellphone.Models;
using WebSellPhoneApiCaller.ApiCaller.ApiCategoryClient;
using WebSellPhoneApiCaller.ApiCaller.ApiProductClient;

namespace Websellphone.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly ICategoryApiClient _categoryApiClient;

        public ProductController(IProductApiClient productApiClient, ICategoryApiClient categoryApiClient)
        {
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
        }
        public async Task<IActionResult> Detail(int id, string culture)
        {
            var product = await _productApiClient.GetById(id, culture);
            return View(new ProductDetailViewModel()
            {
                Product = product,
            });
        }
        public async Task<IActionResult> Category(int id, string culture, int page = 1)
        {
            var products = await _productApiClient.GetPagings(new GetManagerProductPagingRequest()
            {
                CategoryId = id,
                PageIndex = page,
                LanguageId = culture,
                PageSize = 10
            });
            return View(new ProductCategoryViewModel()
            {
                Category = await _categoryApiClient.GetById(culture, id),
                Products = products
            }); ;
        }
    }
}

Websellphone/Views/Product/Category.cshtml
@model ProductCategoryViewModel
@{
    ViewData["Title"] = Model.Category.Name + (Model.Products.PageIndex == 1 ? "" : " - " + _loc["Page"] + " " + Model.Products.PageIndex);
    ViewData["Description"] = Model.Category.Name + (Model.Products.PageIndex == 1 ? "" : " - " + _loc["Page"] + " " + Model.Products.PageIndex);
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture;
}

@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;
<div class="container">
    <ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li class="active">Products Name</li>
</ul>
<h3> @Model.Category.Name <small class="pull-right"> 40 <localize>available products</localize> </small></h3>
<hr class="soft" />
<p>
    Mô tả của ứng dụng (hard)
</p>
<hr class="soft" />

    <div class="row">
      
        <div class="col-md-3">
            <!-- Sidebar content -->
            @await Component.InvokeAsync("SideBar")
        </div>
        <div class="col-md-9">
            <form class="form-horizontal span6">
                <div class="control-group">
                    <label class="control-label alignL"><localize>Sort By</localize> </label>
                    <select>
                        <option>Priduct name A - Z</option>
                        <option>Priduct name Z - A</option>
                        <option>Priduct Stoke</option>
                        <option>Price Lowest first</option>
                    </select>
                </div>
            </form>          
            <br class="clr" />
            <!-- Single product area content -->
            <div class="single-product-area">
                <!-- ... -->
                <div class="tab-content">
                    <div class="tab-pane" id="listView">
                        <div class="row ">
                        @for (int i = 0; i < Model.Products.Items.Count; i++)
                        {
                            var item = Model.Products.Items[i];

                                <div class="col-md-3 col-sm-6">
                                <div class="span2">
                                    <img src="@(Configuration["BaseAddress"] + @item.ThumbnailImage) " alt="@item.Name" />
                                </div>
                                <div class="span4">
                                    <h3><localize>New | Available</localize></h3>
                                    <hr class="soft" />
                                    <h5>@item.Name</h5>
                                    <p>
                                        @item.Description
                                    </p>
                                    <a class="btn btn-small pull-right" href="product_details.html"><localize>Xem chi tiết</localize></a>
                                    <br class="clr" />
                                </div>
                                <div class="span3 alignR">
                                    <form class="form-horizontal qtyFrm">
                                        <h3> @item.Price.ToString("C", culture)</h3>
                                        <label class="checkbox">
                                            <input type="checkbox">  Adds product to compair
                                        </label><br />

                                            <a class="btn btn-add-cart" data-id="@item.Id" href="#"><localize>Add to cart</localize> <i class="icon-shopping-cart"></i></a>
                                        <a href="product_details.html" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                                    </form>
                                </div>
                            </div>                               
                            <hr class="soft" />
                        }
                        </div>
                    </div>

                    <div class="tab-pane active" id="blockView">
                        <ul class="thumbnails">
                            @for (int i = 0; i < Model.Products.Items.Count; i += 3)
                            {
                                <div class="row">
                                    @for (int j = i; j < i + 3 && j < Model.Products.Items.Count; j++)
                                    {
                                        var item = Model.Products.Items[j];
                                        <div class="col-md-4">
                                            <div class="thumbnail">
                                                <a href="/@culture.Name/@_loc["products"]/@item.Id">
                                                    <img src="@(Configuration["BaseAddress"] + @item.ThumbnailImage)" alt="@item.Name" />
                                                </a>
                                                <div class="caption">
                                                    <h5 class="text-center">@item.Name</h5>
                                                    <p class="text-center">@item.Description</p>
                                                    <h4 style="text-align:center">
                                                        <a class="btn btn-add-cart" data-id="@item.Id" href="#"><localize>Add to cart</localize> <i class="icon-shopping-cart"></i></a>
                                                        <a class="btn btn-primary" href="#">@item.Price.ToString("C", culture)</a>
                                                    </h4>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>

                            }
                        </ul>
                        <hr class="soft" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("Pager", Model.Products)
<br class="clr" />

Websellphone/Views/Product/Detail.cshtml
@model ProductDetailViewModel
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture;
}
<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2 localize-content>Shop</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="single-sidebar">
                    <h2 class="sidebar-title">Search Products</h2>
                    <form action="">
                        <input type="text" placeholder="Search products...">
                        <input type="submit" value="Search">
                    </form>
                </div>

                <div class="single-sidebar">
                    <h2 class="sidebar-title">Products</h2>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>
                    </div>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>
                    </div>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>
                    </div>
                    <div class="thubmnail-recent">
                        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$100.00</del>
                        </div>
                    </div>
                </div>

                <div class="single-sidebar">
                    <h2 class="sidebar-title">Recent Posts</h2>
                    <ul>
                        <li><a href="">Sony Smart TV - 2015</a></li>
                        <li><a href="">Sony Smart TV - 2015</a></li>
                        <li><a href="">Sony Smart TV - 2015</a></li>
                        <li><a href="">Sony Smart TV - 2015</a></li>
                        <li><a href="">Sony Smart TV - 2015</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-8">
                <div class="product-content-right">
                    <div class="product-breadcroumb">
                        <a href="/"><localize>Home</localize></a>
                        <a href="">@Model.Product.Name</a>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="product-images">
                                <div class="product-main-img">
                                    <img src="@(Configuration["BaseAddress"] + Model.Product.ThumbnailImage)" alt="">
                                </div>

                                <div class="product-gallery">
                                    <img src="img/product-thumb-1.jpg" alt="">
                                    <img src="img/product-thumb-2.jpg" alt="">
                                    <img src="img/product-thumb-3.jpg" alt="">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="product-inner">
                                <h2 class="product-name">@Model.Product.Name</h2>
                                <div class="product-inner-price">
                                    <ins>@Model.Product.Price</ins> <del>$100.00</del>
                                </div>

                                <form action="" class="cart">
                                    <div class="quantity">
                                        <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity" min="1" step="1">
                                    </div>
                                    <button class="add_to_cart_button btn-add-cart" data-id="@Model.Product.Id" type="submit"><localize>Add to cart</localize></button>
                                </form>

                                <div class="product-inner-category">
                                    <p>Category: <a href="">Summer</a>. Tags: <a href="">awesome</a>, <a href="">best</a>, <a href="">sale</a>, <a href="">shoes</a>. </p>
                                </div>

                                <div role="tabpanel">
                                    <ul class="product-tab" role="tablist">
                                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Description</a></li>
                                        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Reviews</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade in active" id="home">
                                            <h2>Product Details</h2>
                                            <p>
                                                @Html.Raw(Model.Product.Details)
                                            </p>

                                        </div>
                                        <div role="tabpanel" class="tab-pane fade" id="profile">
                                            <h2>Reviews</h2>
                                            <div class="submit-review">
                                                <p><label for="name">Name</label> <input name="name" type="text"></p>
                                                <p><label for="email">Email</label> <input name="email" type="email"></p>
                                                <div class="rating-chooser">
                                                    <p>Your rating</p>

                                                    <div class="rating-wrap-post">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                    </div>
                                                </div>
                                                <p><label for="review">Your review</label> <textarea name="review" id="" cols="30" rows="10"></textarea></p>
                                                <p><input type="submit" value="Submit"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>


                    <div class="related-products-wrapper">
                        <h2 class="related-products-title">Related Products</h2>
                        <div class="related-products-carousel">
                            <div class="single-product">
                                <div class="product-f-image">
                                    <img src="img/product-1.jpg" alt="">
                                    <div class="product-hover">
                                        <a href="" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i><localize>Add to cart</localize></a>
                                        <a href="" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                                    </div>
                                </div>

                                <h2><a href="">@Model.Product.Name</a></h2>

                                <div class="product-carousel-price">
                                    <ins>@Model.Product.Price</ins> <del>$100.00</del>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>