Websellphone/Controllers/ShopPageController.cs
using LazZiya.ExpressLocalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SellPhoneUntilities.Constants;
using System.Diagnostics;
using System.Globalization;
using System.Threading.Tasks;
using Websellphone.Models;
using WebSellPhoneApiCaller.ApiCaller.ApiProductClient;
using WebSellPhoneApiCaller.ApiCaller.ApiSildeClient;

namespace Websellphone.Controllers
{
    public class ShopPageController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ISharedCultureLocalizer _loc;
        private readonly IProductApiClient _productApiClient;

        public ShopPageController(ILogger<HomeController> logger, IProductApiClient productApiClient)
        {
            _logger = logger;
            _productApiClient = productApiClient;
        }
        public async Task<IActionResult> Index()
        {
            var culture = CultureInfo.CurrentCulture.Name;
            var viewModel = new HomeViewModel
            {
                FeaturedProducts = await _productApiClient.GetFeaturedProducts(culture, SystemConstants.ProductSettings.NumberOfFeaturedProducts),
            };
            return View(viewModel);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public async Task<IActionResult> Detail(int id, string culture)
        {
            var product = await _productApiClient.GetById(id, culture);
            return View(new ProductDetailViewModel()
            {
                Product = product
            });
        }
    }
}

Websellphone/Views/Shared/_Layout.cshtml
@{
    var culture = CultureInfo.CurrentCulture.Name;
}
 @inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
 <!DOCTYPE html>

<!--
    ustora by freshdesignweb.com
    Twitter: https://twitter.com/freshdesignweb
    URL: https://www.freshdesignweb.com/ustora/
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/assets/css/owl.carousel.css">
    <link href="~/assets/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <link id="callCss" rel="stylesheet" href="/themes/bootshop/bootstrap.min.css" media="screen" />
    <link href="/themes/css/bootstrap-responsive.min.css" rel="stylesheet" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <input type="hidden" id="hidCulture" value="@culture" />
    <input type="hidden" id="hidBaseAddress" value="@Configuration["BaseAddress"]" />
    <div class="header-area">
        <div class="container">
            <div id="welcomeLine" class="row">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="span6">Welcome!<strong> @User.Identity.Name</strong></div>
                }
                else
                {
                    <div class="span6">Welcome!<strong> Guest!</strong></div>
                }                
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="#"><i class="fa fa-user"></i> My Account</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href="cart.html"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="checkout.html"><i class="fa fa-user"></i> Checkout</a></li>
                                <li>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <form action="/@culture/Account/Logout" method="post">
                                        <button type="submit" style="padding-right:0;margin-top:10px;margin-bottom:0px;background:transparent;border:none;">
                                            <span class="btn btn-large btn-success"><localize>Logout</localize></span>
                                        </button>
                                    </form>
                                }
                                else
                                {
                                    <a href="/@culture/Account/Login"><i class="fa fa-user"></i> <localize>Login</localize></a>
                                }                            
                                </li>
                            <li><a href="/@culture/Account/Register"><i class="fa fa-user"></i> <localize>Register</localize></a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">                              
                                <a style="float:right" href="/en/Home/SetCultureCookie?cltr=en&returnUrl=/en"><span class="" localize-content>English</span></a>
                                <a style="float:right" href="/vi/Home/SetCultureCookie?cltr=en&returnUrl=/vi"><span class="" localize-content>VietNames</span></a>
                            </li>

                            <li >
                               
                            </li>
                            @*<li class="dropdown dropdown-small">
                                <language-nav language-label="NativeName"
                                              cookie-handler-url="@(Url.Action("SetCultureCookie", "Home", new { area= "", cltr="{0}", returnUrl="{1}" }))">
                                </language-nav>
                             </li>*@
                        </ul>
                    </div>
                </div>                
            </div>
        </div>
    </div> <!-- End header area -->

    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="./"><img src="~/assets/img/logo.png"></a></h1>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="/@culture/cart">Cart - <span class="cart-amunt">$100</span> <i class="fa fa-shopping-cart"></i> [ <span id="lbl_number_items_header">0</span> ]</a>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->

    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="ShopPage" asp-action="Index" asp-route-culture="@culture" localize-content>Shop page</a></li>
                        <li><a asp-route-culture="@culture" localize-content>Delivery</a></li>
                        <li><a  href="/@culture/cart" localize-content>Cart</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="#">Category</a></li>
                        <li><a href="#">Others</a></li>
                        <li><a asp-route-culture="@culture" localize-content>Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->
    <!-- Slider -->
    @RenderSection("slider", required: false)

    <!--body-->
    @RenderBody()

    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>u<span>Stora</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Vendor contact</a></li>
                            <li><a href="#">Front page</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="#">Mobile Phone</a></li>
                            <li><a href="#">Home accesseries</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Computer</a></li>
                            <li><a href="#">Gadets</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->
    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/~/assets/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.sticky.js"></script>

    <!-- jQuery easing -->
    <script src="~/assets/js/jquery.easing.1.3.min.js"></script>

    <!-- Main Script -->
    <script src="~/assets/js/main.js"></script>

    <!-- Slider -->
    <script type="text/javascript" src="~/assets/js/bxslider.min.js"></script>
    <script type="text/javascript" src="~/assets/js/script.slider.js"></script>
    <script src="~/js/site.js"></script>
    <script>
        var site = new SiteController();
        site.initialize();
    </script>
    @RenderSection("scripts", required:false)
  
</body>
</html>